# ---------------变量--------------------
ml:
  name: 轻吟剑歌下五湖,心随白云走八荒
  dis: 情不敢至深 恐大梦一场 卦不敢算尽 畏天道无常

eureka:
  instance:
    # 设置微服务调用地址为IP优先
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间 ( 缺省为30s )
    #lease-renewal-interval-in-seconds: 10
    # 发呆时间，即服务续约到期时间 ( 缺省为90s )
    #lease-expiration-duration-in-seconds: 30

  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:1117}/eureka/

#spring:
#  # 指定数据源
#  datasource:
#    url: jdbc:mysql://123.206.125.80:3306/kirito?autoReconnect=true&amp;useUnicode=true
#    username: root
#    password: MyNewPass4!
#    driver-class-name: com.mysql.jdbc.Driver
