# ---------------变量--------------------
ml:
  name: 轻吟剑歌下五湖,心随白云走八荒

eureka:
  instance:
    # 设置微服务调用地址为IP优先
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间 ( 缺省为30s )
    #lease-renewal-interval-in-seconds: 10
    # 发呆时间，即服务续约到期时间 ( 缺省为90s )
    #lease-expiration-duration-in-seconds: 30

  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:1117}/eureka/

