spring:
  cloud:
    config:
      server:
        git:
          # 配置gitlab仓库的地址，注意，此处必须以.git结尾
          uri: https://gitee.com/liangzhong/SpringcloudConfig.git
          # gitlab仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: /config-repo
          username: kirito1117@163.com
          password: kirito1117

eureka:
  instance:
    # 设置微服务调用地址为IP优先
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间 ( 缺省为30s )
    #lease-renewal-interval-in-seconds: 10
    # 发呆时间，即服务续约到期时间 ( 缺省为90s )
    #lease-expiration-duration-in-seconds: 30

  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:1117}/eureka/